### ISSUE TITLE
bzip2::Compression type does not allow arbitrary values from 1-9

### ISSUE THREAD

**Issue by mdsteele** [trifectatechfoundation/bzip2-rs#25]
The `bzip2::Compression` type only allows the options `Fastest` (1), `Default` (6), or `Best` (9).  There seems to be no way to specify a compression level of, say, 4.

Perhaps it would be better to make `bzip2::Compression` work like `flate2::Compression` (which does allow arbitrary numbers), since the two crates already have very similar APIs otherwise?

**Comment by alexcrichton** [comment]
Indeed! They actually started the same way and I haven't gotten around to updating this version :(

I'll try to sync the two APIs this week and hopefully push out a 1.0 as well!

**Comment by dragonmaus** [comment]
Has there been any progress on this issue?

**Comment by alexcrichton** [comment]
Unfortunately no, but some assistance in implementing would be appreciated!

**Comment by dragonmaus** [comment]
Opened #37.
