### ISSUE TITLE
Doesn't seem to have a "raw" module as mentioned in documentation / code comments

### ISSUE THREAD

**Issue by hippietrail** [trifectatechfoundation/bzip2-rs#68]
Places such as this comment in the lib.rs source mention a "raw" module:

https://docs.rs/bzip2/0.4.1/src/bzip2/lib.rs.html#9

//! Access to the raw decompression/compression stream is also provided through
//! the `raw` module which has a much closer interface to libbz2.

But such raw module does not seem to actually exist. If it does and I can't see it because I'm a newbie, it would be good to include an example of how to use it.

**Comment by alexcrichton** [comment]
Ah sorry that's an old comment! It's referring to the `Compress` and `Decompress` structs nowadays.

**Comment by folkertdev** [comment]
fixed by https://github.com/trifectatechfoundation/bzip2-rs/pull/114
